### ISSUE TITLE
720" is alot of seconds

### ISSUE THREAD

**Issue by Fil** [mapbox/sexagesimal#1]
I wonder if the tests and examples with 360" or 720" are not a bit confusing (though mathematically correct) -- given that usually seconds are between 00 and 59.

**Comment by bhousel** [comment]
Closing as stale.  I think it's fine for this library to just handle the odd values.

**Comment by Fil** [comment]
Agree it's fine to handle them, but to show these (and these only) as [examples](https://github.com/mapbox/sexagesimal#example)?

**Comment by bhousel** [comment]
Ohh sorry!  I didn't realize this was about the README page - yeah those examples are bad. 😆
